### ISSUE TITLE
About Karunek's Workshop Luna Coin

### ISSUE THREAD

**Issue by clavera** [AionGermany/aion-germany#100]
I have problem about Karinek's Workshop when im Logout then clik Crafting at Karunek;s Workshop make Luna Coin -2 Like This Screan Shoot
![aion0003](https://user-images.githubusercontent.com/42079372/44942900-1cad4180-ade6-11e8-8644-0c46ef73e9a7.jpg)

**Comment by FrozenKiller35** [comment]
Can you explain it a little more because you wont be able to logout and craft @ the same time :O 
Oh and its -5 on Screen and not -2 ^^

**Comment by clavera** [comment]
yes -5 >.< sory im wrong

**Comment by clavera** [comment]
First im crafting then luna coin stil 0, after that im logout then login again, open karunerk's workshop then clik crafting again then Luna Coin will be minus

**Comment by clavera** [comment]
This A video https://youtu.be/rNnS2rsC9Ac

**Comment by FrozenKiller35** [comment]
Should be fixed with latest REV pls test and give some short response ;)

I also changed the Price from 5 to 2 ;)

**Comment by clavera** [comment]
im use latest REV, then can tell me where location the Price when im must edit ?

**Comment by clavera** [comment]
thank you for info ^^
