### ISSUE TITLE
Emulator Compatibility with OpenJDK 8

### ISSUE THREAD

**Issue by saldru** [AionGermany/aion-germany#102]
Hi Aion Germany team,

I tried to configure an Aion server with your emulator in an Ubuntu 18.04 VM with Java OpenJDK 8 installed but the compilation failed.
I tried to compile it on Windows with Oracle Java SE 8 and the compilation works and I arrive to start the Login and Chat modules but the GameServer module don't start because of incompatibility.

I want to know if the emulator works well with Java 8 ?

Thank you in advance for your reply. :)

Saldru

**Comment by FrozenKiller35** [comment]
GameServer need's Java 7 (1.7)

**Comment by saldru** [comment]
Okay thank you for your help,
I launched the AL-Chat and AL-Login instances with Java 1.8 and AL-Game instance with Java 1.7, it works better but I think I have a problem.

In my AL-Game instance in the [  ### Spawns ###  ] section, I have that : 

> 21:03:32.133 INFO [main]: - [HousingService] Spawned 9 houses in Heiron (id:210040000)
21:03:35.921 INFO [main]: - [HousingService] Spawned 6 houses in Inggison (id:210050000)
21:03:36.514 INFO [main]: - CharlesrunerkAI: Spawned ...

> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
21:05:15.543 WARN [pool-2-thread-20]: - class java.lang.Thread - execution time: 8937msec

> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-2-thread-32"

And nothing move after that. Do you have an idea on what is wrong ?

Thank you for your help. :)

**Comment by FrozenKiller35** [comment]
OutOfMemoryError ;)

Should be min 6GB for Emu (without using GEO files)

**Comment by saldru** [comment]
Okay, yeah I found what it was wrong. my VM have 8Go en RAM put the parameters given for java were not good ! 
Now it's solved. Thank you for you help and your quick answers. :)
