### ISSUE TITLE
Ramdom walk in spawn template

### ISSUE THREAD

**Issue by Papsd** [AionGermany/aion-germany#109]
Hello,

Is it possible to allow directly ramdom walk in the spawn template ?
	
@XmlAttribute(name = "random_walk")
	private Integer randomWalk = 0;

That permiss data Devs to directly random walk an section of NPCs without repeat it for each one.

<spawn npc_id="XXXXXX" respawn_time="295" ramdom_walk="3">
 <spot...
 <spot...
 <spot...
</spawn>

Thanks by advance.

**Comment by FrozenKiller35** [comment]
Sry but this isn't coded and planed yet.
