### ISSUE TITLE
5.8模拟器魔族排行榜不显示你们更新吗

### ISSUE THREAD

**Issue by y123452689** [AionGermany/aion-germany#11]
5.8模拟器魔族排行榜不显示你们更新吗

**Comment by ghostfur** [comment]
English please :) what i need to fix? now chinese food?

**Comment by y123452689** [comment]
Yes, ah, a lot, does it have a commercial version? Download this simulator BUG a lot!

**Comment by y123452689** [comment]
Yes, ah, a lot, does it have a commercial version? Download this simulator BUG a lot!

**Comment by y123452689** [comment]
i am in China! Thanks to Google, there is no way to communicate!

**Comment by ghostfur** [comment]
Aaah now i understand oke sorry! will translate it :)

**Comment by y123452689** [comment]
Do you have a business? Because I'm a newbie, I won't make changes or edits to the version core! Because I haven't studied java, I will make some changes to static! So you want to find a more perfect commercial side and tower friends play together!

**Comment by y123452689** [comment]
Or can I provide a bug from here, can you fix it?
