### ISSUE TITLE
Cap Enchant And Tempering 5.8 | NPC buy spinel medal error

### ISSUE THREAD

**Issue by juangjaguar** [AionGermany/aion-germany#111]
How to create costum caping max enchant and tempering armor, weapon, plume, bracelet, acc ?

I get error npc Prope and Serka [835466,835467] i buy item in this npc use petra medal but the medal not reducing

**Comment by FrozenKiller35** [comment]
If you get an error we need some info about it maybe log with this error

**Comment by juangjaguar** [comment]
That not error but.. we can buy item in that npc [box spinel medal] use 1000 petra medal
but the petra medal not reducing and get the box spinel medal

**Comment by FrozenKiller35** [comment]
If i have some time i'll take a look ;)
