### ISSUE TITLE
initial quest talk to Munin with error

### ISSUE THREAD

**Issue by wellijacob** [AionGermany/aion-germany#119]
initial quest talk to Munin with error
http://myprintscreen.com/s/xuwp/6c05b374e5
![screen-18 25 11 31 10 2018](https://user-images.githubusercontent.com/1711361/47819795-53e29500-dd3a-11e8-9c16-c0a3da8f1891.png)

**Comment by Falke3434** [comment]
not finish Asmodians Quests
