### ISSUE TITLE
5.8 - Error in the moon shop Taki's Mission

### ISSUE THREAD

**Issue by wellijacob** [AionGermany/aion-germany#121]
Error in the moon shop Taki's Mission.
Taki's Mission are having dialog errors, watch the video
[https://streamable.com/lndhc](url)

![screen-18 05 58 06 11 2018](https://user-images.githubusercontent.com/1711361/48090656-b205f100-e1ee-11e8-87ef-5fff365404b8.png)

**Comment by Dhannyjsb** [comment]
I had same problem .

**Comment by Castiel9805** [comment]
I had same problem too, help me please
