### ISSUE TITLE
5.8 - Geo Map - Detecting Ice Layer Morheim, Stairs and other Meshes falling through

### ISSUE THREAD

**Issue by Langerz82** [AionGermany/aion-germany#122]
Hi,

Currently in the Geo Mapping getZ's do not detect when an NPC is on the Ice Layer in Morheim which causes the monsters to fall through when moving. Have we got some code so the ray hits the ice and NOT the physical bottom layer? I'm working on advanced path finding and I need this to be fixed before releasing my code.
Also stairs meshes are not being returned but the physical layer underneath is causing Monsters to fall beneath.
Thanks guys and keep up the good work.

I plan on releasing my A* path finding code to you guys so if you put this in priority or gave me some directions on where to fix I can.

Kind regards.

**Comment by FrozenKiller35** [comment]
Since 4.5 there are no newer working geo files so if the map get's updated from NC the old files won't work correct.

Sry but there is nothing we can do :(
