### ISSUE TITLE
NPC/Monster Move

### ISSUE THREAD

**Issue by Dhannyjsb** [AionGermany/aion-germany#128]
I just realized, NPC and Monster not move and only standing for long time,
I already set gameserver.npcmovement.enable = true at ai.properties. 
can you help me ?
Emu 5.8

**Comment by Dhannyjsb** [comment]
Not Only for 5.8, but Monster on Emu 6.0 not move and wandering . . 

Thanks

**Comment by Dhannyjsb** [comment]
Thank you.

**Comment by TheRealEaro** [comment]
First of all, I'm sorry for the necroing...
I've been tinkering with the emulator for a couple of days now and decided to add some of the missing walk routes, however I couldn't figure if there's a way to make the NPC stay still for a while (I tried repeating the same coordinates a couple of times, but it just ignores it). 
Also is there a known way to make an NPC emote?

**Comment by MariellaDev** [comment]
Look at the TAG **rest_time=x** at the step line to pause at this place.

**Comment by TheRealEaro** [comment]
@MariellaDev Thanks a ton mate!
