### ISSUE TITLE
EXP rate

### ISSUE THREAD

**Issue by Sephiroth91** [AionGermany/aion-germany#134]
Mir ist bei mehreren Versionen (4.8, 5.8 und 6.2) aufgefallen das wenn alle rates auf x1 stehen und zusätzliche rates wie holiday boost deaktiviert sind alle Monster knapp das doppelte an EXP geben als sie sollten. Es könnte auch nur x1,9 sein es war glaube ich nicht exakt das doppelte. Aufgefallen ist es mir als ich einen Sprigg Worker der laut static_data eintrag etwas mehr als 200exp gibt und man von Level 1 auf 2 aber 400 EXP braucht ich trotzdem Level 2 war nach einem Kill. Ich tötete weitere Monster in Ishalgen in allen Levelbereichen und alle gaben mehr als sie eigentlich sollten.

**Comment by FrozenKiller35** [comment]
Hab für 5.8 mal nen fix hochgeladen bitte testen und berichten ;)

**Comment by Sephiroth91** [comment]
So ich konnte es endlich testen :)
Es Funktioniert das Monster sollte 111 exp geben laut static_data und ich habe 111 exp bekommen. Auch mit dem Level hatte ich keine Probleme das blieb alles wie es sein sollte(Im Forum schrieb ja jemand das sein Level immer auf 1 zurückgesetzt wird). Was mir aber noch aufgefallen ist im Systemmenü funktioniert der Zähler für abgeschlossene Queste wie er es soll aber nachdem ich den Server einmal neugestartet habe war der Zähler wieder auf 0. Ich weis nicht ob das nicht von vorne rein nur temporär sein soll oder ob das eigentlich dauerhaft gespeichert sein soll wie viele Queste man abgeschlossen hat aber dauerhaft erscheint mir sinnvoller. Der Zähler für Monster kills funktioniert gar nicht da wird nichts gezählt.

**Comment by FrozenKiller35** [comment]
Der Zähler resettet ist immer nur Temp auch auf dem Offi warum er keine Mobs zählt weis ich leider nicht dafür gibt es kein Serverpaket.

BTW die EXP-Werte sind nicht alle richtig die sind leider nicht im Client verteckt sondern stammen vom sniffen auf dem Offi wenn wir keine Werte haben ist er default auf 10K EXP.
Kurz gesagt du kannst sie dir einstellen wie du magst im Template^^

**Comment by Sephiroth91** [comment]
Das mit dem Zähler finde ich ja irgendwie sinnlos da das gesamt Ergebnis für mich viel interessanter wäre aber wenn es sogar so auf dem Offi ist dann auch nicht weiter relevant. Das mit dem Template hatte ich schon gesehen da werde ich in der Zukunft auch noch etwas dran rum werkeln. Der Fix das nun aber alle Monster geben was auch eingetragen ist müsste aber noch auf 6.2 in der Zukunft übertragen werden :) Dann kann das hier auch geschlossen werden.

**Comment by FrozenKiller35** [comment]
Ja für 6.2 hab ich das auch noch vor aber ich hoffe erstmal auf mehr Rückmeldungen vlt findet ja einer doch noch einen Fehler aber du kanst ja im SVN sehen was geändert wurde und es für dich erstmal in 6.2 ändern ;)

**Comment by SamDreamsMaker** [comment]
Hi, thanks a lot for this amazing work.
I have a question, what is the file for the EXP rate ?
I searched but I was just able to find a value 1 by default (2-3 for VIPs)
