### ISSUE TITLE
change server time

### ISSUE THREAD

**Issue by steven90005** [AionGermany/aion-germany#136]
I want to change my server time zone.

I edit my gameserver.timezone to Etc/GMT-8 or Asia/Taipei
and  SM_VERSION_CHECK.java  from this website:
http://falke34.bplaced.net/forums/archive/index.php?thread-3168.html

but these still don't work :(
My emu version is 4.7.5.

**Comment by FrozenKiller35** [comment]
writeD(28800) should -8 Hours

**Comment by FrozenKiller35** [comment]
Dont know if this works but try this

writeD((int) (Calendar.getInstance().getTimeInMillis() / 1000));
writeH(350);//4.3
writeH(2561);//4.5

Change Both H to 1 D:

writeD((int) (Calendar.getInstance().getTimeInMillis() / 1000));
writeD(28800);

if this isnt working you also can try to add this change too :

writeC(GSConfig.SERVER_COUNTRY_CODE);// country code;
writeC(0x00);// unk

to 
writeC(GSConfig.SERVER_COUNTRY_CODE);// country code;
// writeC(0x00);// unk

**Comment by steven90005** [comment]
Thanks for your answer
I try to change both H to 1 D like that:

writeD((int) (Calendar.getInstance().getTimeInMillis() / 1000));
		writeD(28800);
        //writeH(350);//4.3
        //writeH(2561);//4.5
        //writeH(2561);//4.5
        //writeH(5140);//4.5
        //writeH(276);//4.5
        //writeH(2);//4.5
        writeC(GSConfig.CHARACTER_REENTRY_TIME);

and this really changed the time of my server,
but the year turns into 19XX and month, day, time are all wrong.

so i try 

writeC(GSConfig.SERVER_COUNTRY_CODE);// country code;
// writeC(0x00);// unk

but still wrong.

My SM_VERSION_CHECK.java is using this:
https://github.com/GiGatR00n/Aion-Core-v4.7.5/blob/master/AC-Game/src/com/aionemu/gameserver/network/aion/serverpackets/SM_VERSION_CHECK.java
