### ISSUE TITLE
Not Playable

### ISSUE THREAD

**Issue by Paranoid555** [AionGermany/aion-germany#14]
after like 6 hours of trying to make this server work, i came across those problems.

"cannot find or load main class com.aionemu..."
"error opening zip file or JAR manifest missing : libs/al.commons"

and the AL_Login.jar is missing...

and others like this..
if there is a solution please let me know..

**Comment by FrozenKiller35** [comment]
You have to compile the Emu so after DL you should use build_chatserver.bat, build_gameserver.bat and build_loginserver.bat.

After successfull Build you have all you need to start ;) 
Example:
AL-Game\build\dist\AL-Game  --> StartGS.bat  etc

**Comment by Paranoid555** [comment]
Im Sorry, im a total noob.

i managed to read about Ant and Enviroment Variables.
now everything is working only need to setup database and test it. thanks for replay :)

**Comment by FrozenKiller35** [comment]
You're welcome
