### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by danny1991** [AionGermany/aion-germany#140]
[error.log](https://github.com/AionGermany/aion-germany/files/3117954/error.log)

I setup to work with jdk1.8 but idk if is from that, any ideas?

**Comment by elineda** [comment]
you need to run gameserver with jdk7


https://mega.nz/#!UlJUQKxA!nCWwEWLv43kdlnkIK7xJq1GOppyw1i5S2AbCQCPi5M4

**Comment by FrozenKiller35** [comment]
Login and Chat Server are working with 1.8 but GameServer still need 1.7

**Comment by danny1991** [comment]
oooh that why, thanks for support
