### ISSUE TITLE
Aion-Germany

### ISSUE THREAD

**Issue by hamdi061** [AionGermany/aion-germany#147]
hello

we can't register. Could you please activate the record.

**Comment by y123452689** [comment]
7.0






------------------ 原始邮件 ------------------
发件人: "hamdi061"<notifications@github.com>;
发送时间: 2019年5月11日(星期六) 凌晨2:11
收件人: "AionGermany/aion-germany"<aion-germany@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [AionGermany/aion-germany] Aion-Germany (#147)




hello
 
we can't register. Could you please activate the record.

**Comment by y123452689** [comment]
27/5000

 
Hello, when will you update your new job






------------------ 原始邮件 ------------------
发件人: "hamdi061"<notifications@github.com>;
发送时间: 2019年5月11日(星期六) 凌晨2:11
收件人: "AionGermany/aion-germany"<aion-germany@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [AionGermany/aion-germany] Aion-Germany (#147)




hello
 
we can't register. Could you please activate the record.

**Comment by hamdi061** [comment]
ı don't understand

**Comment by hamdi061** [comment]
http://falke34.bplaced.net/forums not active mail send :/
