### ISSUE TITLE
Progressive

### ISSUE THREAD

**Issue by Dixdros** [AionGermany/aion-germany#148]
Hallo es ist jetzt kein Fehler und ich kenne mich mit GitHub nicht so sehr aus deswegen erstelle ich hier mal mein Wunsch.

Es wäre super schön zu sehen wie weit in (%-zahlen) die verschiedenen Versionen (5.8 , 6.5) sind somit würde man die verschiedenen versionen denke ich mal eher testen. und kann man überhaupt von 5.8 auf 6.5 seine chars rüber transfern ?

**Comment by FrozenKiller35** [comment]
Hallo, leider ist das nicht möglich mit den % da wir immer nur updaten auf die neue Version (außer 5.8) und dann fangen wir immer beim letzten Stand der vorherigen Version wieder an und updaten / ergänzen, da wir nur zu 2 sind hängen wir auch immer hinterher. Ein Transfer ist nicht vorgesehen da uns dafür die Zeit fehlt meistens ist er aber mit den SQL updates aber trotzdem machbar.
