### ISSUE TITLE
Mobs kill as soon as you attack

### ISSUE THREAD

**Issue by kittykatklawz** [AionGermany/aion-germany#154]
Hello,

First off, thank you for all your hard work with this project! 

I have created a server, which connects perfectly. When I tested the experience rate, as soon as I attack a mob, with a sword, I die immediately. If I use a spell and the mob does not touch me, I can kill it. As soon as I kill it, the first initial attack it huge and it one shots me dead. I am wondering how I can change this so that I can actually play the game.

Thank you in advance for your help.

**Comment by FrozenKiller35** [comment]
You can't do anything but its on our Todo list

**Comment by kittykatklawz** [comment]
I figured it was on the todo list. Thank you for the response.

**Comment by chow007** [comment]
This is the problem that NPC attacks are too high. I have fixed that the path is npc_templates.xml

**Comment by axiscat** [comment]
did this bug fixed ?

**Comment by SamDreamsMaker** [comment]
Hi, same for me, I tried to find how fix it but there is some many calculations :O
I don't know if it's a setting file for speed animations, a calculation error, a stat setting file for damage.
If someone can help us. just...=> Thanks !
