### ISSUE TITLE
Abyss siege bugs [5.8]

### ISSUE THREAD

**Issue by TheRealEaro** [AionGermany/aion-germany#158]
Hello,
I've noticed that Abyss sieges Have some problems. Since the position of the forts have been changed in 5.3 I think, the faction NPC's are missing (their position haven't been changed) and the shields/barriers around the forts are not working. I can fix the NPC's positions, probably the shield positions as well, however, siege weapons can't be summoned as well. I checked some files and found a tag usearea="_ABYSS_CASTLE_AREA_" but could't find where the _ABYSS_CASTLE_AREA_ value is defined. 

Thought I might report it here.

**Comment by FrozenKiller35** [comment]
Pls check the Abyss Zone file for the correct Tag
