### ISSUE TITLE
Magic boost not working properly.

### ISSUE THREAD

**Issue by Paranoid555** [AionGermany/aion-germany#16]
I tried to get max magic boost of 7k on sorc, and its seems like the skills only do 100% dmg and not counting the magic boost.

Its not suppost to be like that i think. Please reply.

**Comment by FrozenKiller35** [comment]
Stats are the most hardest part in this game but we are working on it ;)

**Comment by FrozenKiller35** [comment]
Played around a little and now i krit (36.788) on dummy target with Illusion Storm(Level 6) and 7.3k Mboost

**Comment by ghostfur** [comment]
Falke didnt you guys see my new pushes? because i did skill animation + event window!

**Comment by FrozenKiller35** [comment]
Nothing to see here in GitHub

https://prnt.sc/jt294i

**Comment by ghostfur** [comment]
![4](https://user-images.githubusercontent.com/13853736/41196308-f2ea763c-6c3c-11e8-883a-728dbb9c91e5.PNG)
This is what i get!

**Comment by sagase** [comment]
Hi, where do you go to edit magic boost cap is something in static_data?
