### ISSUE TITLE
[7.0] Summons do nothing ..

### ISSUE THREAD

**Issue by teddy258** [AionGermany/aion-germany#161]
Spirit-Master's Summons do not move, attack, skill at all, and do not work.
I want to know why
thank you.

**Comment by teddy258** [comment]
From client
Packets such as CM_SUMMON_MOVE are not received.

Is this a problem on the server side? The client may not be able to receive the SM_SOMMON_UPDATE packet from the server.

**Comment by teddy258** [comment]
As a result of the check, Client can receive the SM_SOMMON_UPDATE packet from the Server. The client then fails to send CM_SOMMON_MOVE, CM_SOMMON_ATTACK, CM_SUMMON_CESTSPELL, packets.
How do i solve this problem ?
Is this the client's problem ? T. T
I need help..

**Comment by kortana13400** [comment]
Coz packet in 7.x are not good, only.
Change packet and all thing reworking.

**Comment by teddy258** [comment]
ok.. thx

**Comment by FrozenKiller35** [comment]
Fixed with latest REV
