### ISSUE TITLE
NA Version

### ISSUE THREAD

**Issue by DemonRem** [AionGermany/aion-germany#165]
can its work for the NA version too?

**Comment by chow007** [comment]
yes



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DemonRem"<notifications@github.com&gt;; 
发送时间: 2019年11月5日(星期二) 中午11:36
收件人: "AionGermany/aion-germany"<aion-germany@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [AionGermany/aion-germany] NA Version (#165)




can its work for the NA version too?

**Comment by DemonRem** [comment]
Nice thank.
