### ISSUE TITLE
7.2 - Class resetting

### ISSUE THREAD

**Issue by Jawarii** [AionGermany/aion-germany#166]
Choosing any class at beginning usually shows up as warrior.

After changing class and even leveling to 80 (or any level), if you use a skill on mobs or Glide, class resets to warrior no matter what class you were (you keep the skills though) however you wont be able to access daevanion skills or be able to fly/glide, due to not being a "daeva" anymore.

**Comment by FrozenKiller35** [comment]
Any Error's in console Log ?

**Comment by Jawarii** [comment]
No, there are no errors showing up when this occurs.

Also one more thing I noticed is that apparently you are always showing as "Warrior" in profile window, before even doing anything to produce the reset bug, which means that for some reason you are always being considered as a warrior, which is interestingly, defined as "0" in classes, which might indicate where the issue lies.

I tried looking around a lot but couldn't reach anything.

**Comment by Jawarii** [comment]
Are you experiencing the same problem too ?

**Comment by FrozenKiller35** [comment]
No thats why i ask for Error's in console Log

**Comment by Jawarii** [comment]
hmm, the errors i get in console are when starting the server and they are related to housing, but ill attach the errors in here either way and you can take a look at them if you want
[error.log](https://github.com/AionGermany/aion-germany/files/3848455/error.log)

**Comment by Jawarii** [comment]
can you just tell me what java versions, database for mysql, and sql server u guys use ? so i can 100% do it like u do it ? thanks in advance

**Comment by Falke3434** [comment]
I use this: https://sourceforge.net/projects/miniserver/files/Uniform%20Server%20ZeroXI/11_8_2_ZeroXI/

**Comment by Jawarii** [comment]
XI for some reason does not work for me when i execute SQL files, i get errors, however XIII works perfectly fine.
Can I contact you some other way other than here ?

**Comment by Jawarii** [comment]
I've been trying to fix this issue for over a week now, I don't want to be a spammer or an annoying nagging person, but would be nice if i get a little bit of help.

I've tried 6.2 files that I had saved up from before and found my self a 6.2 client, and that issue did not occur there, things were totally fine.

So my only assumptions are either there's something wrong with the 7.2 files i'm downloading here, or the 7.2 client I'm using, which is a FRESH gameforge 7.2 client, which kinda shouldn't cause any issues, should it ?

Did anything change in the way I'm supposed to do things from the 6.2 files to the 7.2 files?

**Comment by Jawarii** [comment]
There's how it looks ingame, an artist labeled as Warrior:
[(https://i.gyazo.com/f56fd634c1d9e23f2e6a52b5ff75af34.jpg)]

**Comment by FrozenKiller35** [comment]
If i have some time i'll check it

**Comment by Jawarii** [comment]
i figured out the issue, it was in SM_STATS_INFO, this packet needs a lot of fixing.

**Comment by FrozenKiller35** [comment]
Class Bug fixed
