### ISSUE TITLE
5.8 asmodinans character hair wrong in  character selection screen

### ISSUE THREAD

**Issue by 14635956** [AionGermany/aion-germany#167]
create a asmodians character with a hair style  return to character selection screen hair style will change 
enter game hair style its ok

test on bin32 aion.bin and bin64 aion.bin NA client

maybe relevant  to PlayerInfo.java writeD(raceId);  but I dont know how to fix

**Comment by 14635956** [comment]
whatever which faction I choice character selection screen only show elyos data
I can't figure raceId out  for let it work correct

**Comment by Falke3434** [comment]
Support only for GF (EU) Client!

**Comment by 14635956** [comment]
sounds so sadly  but thanks
how do I download EU 5.8 client (gameforge now its 7.2)
do you upload this client to somewhere like google driver or mega where I can donwload it 
please
