### ISSUE TITLE
One small bug after last fix

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#17]
You added:  addPacketOpcode(SM_EVENT_WINDOW.class, 0x154, idSet);
but this colliding with:  addPacketOpcode(SM_BATTLEFIELD_UNION_REGISTER.class, 0x154, idSet);

(the same OPCODES)

and bug on the console arrived.

I changed: addPacketOpcode(SM_EVENT_WINDOW.class, 0x154, idSet);
to:
addPacketOpcode(SM_EVENT_WINDOW.class, 0x153, idSet);

154 -> 153 OPCODE

Is this correct now ?

**Comment by FrozenKiller35** [comment]
No Event is 154 but we have to find the new Battlefield OPCODE

**Comment by benas80** [comment]
Yea, i comment it :) (2 slashes added)
