### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Vieka** [AionGermany/aion-germany#172]
hello when will they publish an update? :)

query, when I activate the sieges for example, / siege start 1921, the fortress becomes vulnerable and invunerable immediately, I do not know what the problem is, in addition to the skills there are some that do not run and only remain loading and the other if I look for any armor or weapon the character does not open them.

**Comment by Vieka** [comment]
Do you also close the subject?

**Comment by Vieka** [comment]
What is the idea of ​​being able to ask questions and do not answer and also close the subject?

**Comment by FrozenKiller35** [comment]
Sieges are one of the last thing's on our Todo and already asked many many times ;)
So the answer for when is we don't know it yet

**Comment by Vieka** [comment]
Thank you very much for the frozen response, even if there is no solution at the moment, I appreciate your attention to my problem. greetings from Chile.
