### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by Jawarii** [AionGermany/aion-germany#174]
Hello, the stats ever since 6.x changed and right now it seems that Magic Defense is being put as Magical Resist in your XML files on certain items/skills.

I want to ask how do you automatically apply extracts to XML, and where can I edit these converts to do it on my own.

Thanks.

**Comment by Jawarii** [comment]
would be nice if you would share your parser, thanks.

**Comment by Falke3434** [comment]
We will not publish the parser
