### ISSUE TITLE
7.2 [ReadWrite-0 Dispatcher]

### ISSUE THREAD

**Issue by dashuiguo520** [AionGermany/aion-germany#175]
[ReadWrite-0 Dispatcher]:Unknown packet received from Aion client: 0x00BA, state=IN_GAME
0000: E8 1B 03 00

**Comment by dashuiguo520** [comment]
Unknown packet received from Aion client: 0x013D, state=IN_GAME
0000: B1 97 01 00 00 00 22 00 31 00 22 00 00 00          ......".1."...

**Comment by dashuiguo520** [comment]
11:06:18.706 WARN [ReadWrite-0 Dispatcher]: - Unknown packet received from Aion client: 0x00BA, state=IN_GAME
0000: 2B 18 03 00                                        +...
11:06:54.676 WARN [ReadWrite-0 Dispatcher]: - Unknown packet received from Aion client: 0x00BA, state=IN_GAME
0000: 2B 18 03 00                                        +...

**Comment by FrozenKiller35** [comment]
THX 0x00BA can be ignored for now 0x013D whe are on it ;) But you can help us if you know what you have done to receive 0x013D

**Comment by Falke3434** [comment]
0x13D was fixed with one of the latest revisions....
