### ISSUE TITLE
Quest ascension lvl9

### ISSUE THREAD

**Issue by darkmoi31** [AionGermany/aion-germany#178]
Hier,

I have a bug with ascension quest (lvl9)
When i speaker to the and exit window quest, i can't complete quest. Can you help me ?

Thanks

**Comment by thepny** [comment]
Hi,
find rae quest does not work (id: 70006)
after tricking in database - also cant enter haramel

**Comment by FrozenKiller35** [comment]
Thx for report

**Comment by Falke3434** [comment]
Poeta and Ishalgen Kamp Quests will add in the next days...
