### ISSUE TITLE
About Geodata

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#18]
Maybe someone have updated geodata builder (with collision flags) ?
Collision flags are very important, defining inside of object (building,caves and others)
Or how to receive this collision info flags?
Generally we have 5.8 version and most maps changed from 4.8 version.(there are some terrain+objects differences in many maps, and there are new maps).

**Comment by FrozenKiller35** [comment]
Sry but we dont have them and we dont know someone who can build them :(
