### ISSUE TITLE
Do all data need to be redone now? Too many questions! !!

### ISSUE THREAD

**Issue by jielcc2** [AionGermany/aion-germany#180]
The current server lacks a lot of static data, if I need to redo, I think I should be able to play something

**Comment by FrozenKiller35** [comment]
?????????

**Comment by jielcc2** [comment]
I checked the server, a lot of data is missing, the opcode is missing, the data is missing, if the transfer, binding point, NPC attributes. . . Wait, if I can, I'd like to help the project
