### ISSUE TITLE
BUG Report Item ID190095111

### ISSUE THREAD

**Issue by chow007** [AionGermany/aion-germany#181]
Dear developer, Hello: I have a problem here. When I use the item ID190095111, my client program will stop and the game will not work properly. Please fix it. Thank you @Falke3434 
![use](https://user-images.githubusercontent.com/52728297/76081058-4949a700-5fe3-11ea-821c-9a0aa8d82d14.jpg)
![item-190095111](https://user-images.githubusercontent.com/52728297/76081061-4b136a80-5fe3-11ea-8d14-cfe8f0438a44.jpg)

**Comment by FrozenKiller35** [comment]
Use latest GF Client and it will not Crash but its still in Development

**Comment by chow007** [comment]
GF Client  the same

**Comment by cebols-game** [comment]
work fine for me using NCsoft april update client
