### ISSUE TITLE
 chat system

### ISSUE THREAD

**Issue by jielcc2** [AionGermany/aion-germany#182]
Starting from 5.8, the chat system seems to be unable to work properly. I want to say / 1, / 2ande / 3, it seems that I need to recheck

**Comment by 14635956** [comment]
you need version.dll 
please google zzsort version.dll

**Comment by 14635956** [comment]
here you will get chat server work
https://github.com/zzsort/Aion-Version-Dll

**Comment by jielcc2** [comment]
Thanks, the chat server has started to work, but I am not sure if it is a DLL file problem

**Comment by 14635956** [comment]
you are welcome you can use different vesion.dll and try use find command for look ip and port taht  client connected ------------------ 原始邮件 ------------------
发件人: "jielcc2"<notifications@github.com>
发送时间: 2020年4月22日(星期三) 下午4:47
收件人: "AionGermany/aion-germany"<aion-germany@noreply.github.com>;
抄送: "14635956"<14635956@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [AionGermany/aion-germany]  chat system (#182)




 
Thanks, the chat server has started to work, but I am not sure if it is a DLL file problem
 
&mdash;
