### ISSUE TITLE
Monster rebound damage high

### ISSUE THREAD

**Issue by xiyouxi66** [AionGermany/aion-germany#183]
Hello, first of all, thank you for your hard work for this project!

I've created a server that connects perfectly. You can also enter the game smoothly. When attacking monsters in close combat, they will die at a stroke. The characters will also die from the damage of the resilience of monsters. How to deal with this? Thank you for your help!

**Comment by jielcc2** [comment]
You need to modify the NPC attribute, because his attack is too high

**Comment by jielcc2** [comment]
You need to modify the NPC attribute, because his attack is too high，Should solve your problem

**Comment by xiyouxi66** [comment]
谢谢

Thank you

> 您需要修改NPC属性，因为他的攻击力太高，应该可以解决您的问题


Thank you
