### ISSUE TITLE
Too many packets are missing

### ISSUE THREAD

**Issue by jielcc2** [AionGermany/aion-germany#184]
The server is missing too many packets. Is anyone still repairing and updating? Is the administrator here? Is it possible to leave contact information?
![1](https://user-images.githubusercontent.com/55610637/76740569-0e94fb00-67a9-11ea-933a-366189ab9ab3.png)

**Comment by Falke3434** [comment]
1 packet? 
Help us....you can sniff it with PacketSamurai (on SVN)

**Comment by jielcc2** [comment]
First you need to add me to SVN

**Comment by Falke3434** [comment]
Why? Create your own Fork from this repo
