### ISSUE TITLE
Latest client version not working, which one is supported?

### ISSUE THREAD

**Issue by Power2All** [AionGermany/aion-germany#185]
I need to know, so I can start working on this emu as well.

**Comment by Falke3434** [comment]
7.2/3 Gameforge Client is working

**Comment by Power2All** [comment]
Got it working, took a while to figure out why it wasn't working, thanks !

**Comment by Rusah** [comment]
@Power2All So what was the issue? I'm getting stuck on the server select.

**Comment by Power2All** [comment]
Pure configuration.
These are the important stuff:

ipconfig.xml in your configuration could be the issue.
<ipconfig default="ip.to.listen.on"></ipconfig>
If this is not correctly set, it could be troublesome.
After I got this correctly set, it worked.

**Comment by Rusah** [comment]
Appreciate the follow up. I'll give that a shot.

**Comment by Rusah** [comment]
I imagine the default ought to be fine. The game server and login server are connecting fine, but my client hangs on hitting the 'Join server' button after login. Console information is as follows:

https://i.imgur.com/oVrPMwF.png

And I don't see anything terribly helpful in the logs. Where is the setting for enabling debug?
