### ISSUE TITLE
hello Did you know how to implement dialogue title?

### ISSUE THREAD

**Issue by 14635956** [AionGermany/aion-germany#188]
how to implement dialogue title ?
thank you
I'am very poor in packet structure reverse

**Comment by chow007** [comment]
yes  you neeed webserver and translate Client and server secret key

**Comment by 14635956** [comment]
can you give me some example for implement it?
I can't figure out how to do it

**Comment by 14635956** [comment]
@chow007  please thank you

**Comment by githwc** [comment]
> yes you neeed webserver and translate Client and server secret key

Hello, my web server has been implemented, but the dialog title cannot be displayed. I guess it is related to SM_L2AUTH_LOGIN_CHECK, but I don't know how to generate the value of hex
