### ISSUE TITLE
Small problem with Book of Monsters

### ISSUE THREAD

**Issue by alexkulya** [AionGermany/aion-germany#19]
![screenshot_1](https://user-images.githubusercontent.com/7693165/40626702-ecf9c5c6-62c2-11e8-9b7f-2d8769f1e22c.png)

When you kill mob Moonlight Spirit counts mob Kselliki and so on with the others. Use Gameforge client.

P.S. Sorry for the bad English.

**Comment by FrozenKiller35** [comment]
THX

**Comment by FrozenKiller35** [comment]
Update:
Pls check latest REV

**Comment by alexkulya** [comment]
Checked. Work perfectly. Thanks.
