### ISSUE TITLE
7.3Equipment identification

### ISSUE THREAD

**Issue by jielcc2** [AionGermany/aion-germany#193]
All 7.3 devices cannot be identified, I am checking

**Comment by Vieka** [comment]
The same thing happens to me, I even have problems with the flag file

**Comment by mino3d** [comment]
How can any of you help me test this Aion server?

**Comment by KurioSowrd** [comment]
My gsService has a XML error, <itemTemplate > read a row has no end </itemTemplate>  it is my problem?

**Comment by sve1r** [comment]
> My gsService has a XML error, read a row has no end it is my problem?

Element type "item_template" must be followed by either attribute specifications, ">" or "/>". 

Yep. Not only u. Mine also

**Comment by jielcc2** [comment]
You can add my Rinne, where can I talk about what issues
@9924













At 2020-07-26 11:13:20, "SVE1R" <notifications@github.com> wrote:

My gsService has a XML error, read a row has no end it is my problem?

Element type "item_template" must be followed by either attribute specifications, ">" or "/>".

Yep. Not only u. Mine also
