### ISSUE TITLE
Custom Launcher

### ISSUE THREAD

**Issue by PatrickSantoZZ** [AionGermany/aion-germany#194]
Isnt it anymore possible to connect with a custom launcher/batch file to the gameserver? 
do we really need the launcher from your files to connect?

if there is still a way to connect without it would be nice to get more infos about it.

ty~

**Comment by jielcc2** [comment]
Not required, there are many ways to start, you can choose freely

**Comment by FrozenKiller35** [comment]
@jielcc2 you should be more precise for him ;)
