### ISSUE TITLE
Luna Points

### ISSUE THREAD

**Issue by ghostfur** [AionGermany/aion-germany#20]
When you add luna to yourself like for example  ( //set luna 500) it giving luna coins but after a relog
all luna is gone so it doesnt stay inside db  al_server_ls ? i tryed to change amounth inside the database but also has no effect 

Greetings!

**Comment by FrozenKiller35** [comment]
Yes it's possible 
Some little magic for the GS batch files:
SET PATH="C:\Program Files\Java\jdk1.7.0_80\bin" ;)

**Comment by ghostfur** [comment]
Yes haha i have found it after you put the messenger :D ! will fix it now thanks for all help! haha

**Comment by ghostfur** [comment]
Luna works perfect now! :) it was the login server thanks!
