### ISSUE TITLE
NPCs not moving.

### ISSUE THREAD

**Issue by penguinjoe** [AionGermany/aion-germany#201]
Appears mob NPCs are not moving in v7.5.
gameserver.npcmovement.enable = **true** in ai.properties

**Comment by FrozenKiller35** [comment]
They cant move without Walker's or random walk ;)

**Comment by penguinjoe** [comment]
Since I have large amount of memory to work with I tried the suggestion (for 5.8) here (random_walk): 
https://github.com/AionGermany/aion-germany/issues/128
Did not work

**Comment by FrozenKiller35** [comment]
I can't find any problem, its working without any issue, did you clean the cache folder after adding random_walk="10" to you NPC spots ?

Example:

<spawn npc_id="651844" respawn_time="295">
	<spot x="633.10864" y="951.3188" z="100.50044" h="9" random_walk="10"/>
	<spot x="621.8091" y="960.20544" z="100.33984" h="57" random_walk="10"/>
	<spot x="623.53455" y="942.4942" z="100.438225" h="68" random_walk="10"/>
	<spot x="623.062" y="947.03845" z="99.587204" h="11" random_walk="10"/>
	<spot x="610.8765" y="959.93646" z="99.37723" h="32" random_walk="10"/>
	<spot x="602.15894" y="987.9753" z="99.50618" h="0" random_walk="10"/>
	<spot x="605.62274" y="972.96796" z="99.479965" h="82" random_walk="10"/>
	<spot x="583.56854" y="1036.9434" z="100.6007" h="87" random_walk="10"/>
	<spot x="581.1025" y="1038.3793" z="100.89432" h="106" random_walk="10"/>
</spawn>


Proof:
https://youtu.be/U0lg3owlvWQ

**Comment by penguinjoe** [comment]
Thanks.

**Comment by penguinjoe** [comment]
thanks.
