### ISSUE TITLE
VIP system

### ISSUE THREAD

**Issue by qingqing1988** [AionGermany/aion-germany#203]
Do you know the AION-VIP function? Can you make it?

**Comment by Valerius997** [comment]
hey you have problem with weapon? can't equip can't do identification? with all class

**Comment by y123452689** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AionGermany/aion-germany"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月2日(星期五) 凌晨1:24
收件人:&nbsp;"AionGermany/aion-germany"<aion-germany@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[AionGermany/aion-germany] VIP system (#203)





 
Do you know the AION-VIP function? Can you make it?

**Comment by qingqing1988** [comment]
![1](https://user-images.githubusercontent.com/59536273/98708214-e43d2100-23bb-11eb-8f64-63aac0f291a1.png)

**Comment by qingqing1988** [comment]
Can you implement this function?
