### ISSUE TITLE
Can login but can't join to the server

### ISSUE THREAD

**Issue by LeagueAddons** [AionGermany/aion-germany#204]
Hello.
I have problem with joining to the server.
When i select server and i press "Join" my game only freeze and i can't join.
In Game Server Console i have "INFO [Accept Dispatcher]: - connection from: 127.0.0.1"

**Comment by Falke3434** [comment]
Please check LoginServer -> log -> Error.log

**Comment by fikrivoxel** [comment]
i got same error but log in error its empty
