### ISSUE TITLE
Cube Expansion Problem

### ISSUE THREAD

**Issue by alexkulya** [AionGermany/aion-germany#21]
![screenshot_1](https://user-images.githubusercontent.com/7693165/40887801-ba6d0512-6756-11e8-95f1-07670cffd292.png)

It is impossible expand the inventory to level 11.
Cube Expansion Key are present in the inventory, and when you try to improve they are not used.
Either I do something wrong or the keys don't work.

**Comment by FrozenKiller35** [comment]
Its all about the Client and Keys, GF Client uses other Keys then NA Client ;)

**Comment by alexkulya** [comment]
Thank you for the information. It's decided. My inattention is astounding :)
