### ISSUE TITLE
Aion GF 7.8 : No game server is available to the authorization server (6)

### ISSUE THREAD

**Issue by saitokojiro** [AionGermany/aion-germany#212]
with a similar country code for the game and the server but when you try to connect to a server you get the error "No game server is available to the authorization server (6)".

**Comment by Jawarii** [comment]
I've got the same issue, everything was working fine until 7.8 I started getting this error aswell.

**Comment by CrimsonDespair** [comment]
Can confirm. Same problem. Still there.

**Comment by IMirrror** [comment]
7.8  version.dll     download addr？

**Comment by Synna** [comment]
Hello, I have the same problem with the 64bit client.
I manage to enter in the game with the 32bits client but the game crashes after the character selection (I can see my character in the game and the login message but it crashes before I can move).

Ps: Congratulations for your work!

**Comment by IMirrror** [comment]
oh，I hope&nbsp; ur&nbsp; team&nbsp; &nbsp;make&nbsp; bin64&nbsp; version 。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AionGermany/aion-germany"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 晚上9:37
收件人:&nbsp;"AionGermany/aion-germany"<aion-germany@noreply.github.com&gt;;
抄送:&nbsp;"天上人间"<771259@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [AionGermany/aion-germany] Aion GF 7.8 : No game server is available to the authorization server (6) (#212)





 
Hello, I have the same problem with the 64bit client.
 I manage to enter in the game with the 32bits client but the game crashes after the character selection (I can see my character in the game and the login message but it crashes before I can move).
 
Ps: Congratulations for your work!

**Comment by Jawarii** [comment]
anyone of you guys got any fix for this yet ?

**Comment by Synna** [comment]
no I haven't found a solution on my side but I'm interested if any of you have one

From what I understand the project is stopped?

**Comment by Jawarii** [comment]
seems like it yeah, i dont mind it being stopped, i just want to be directed in the right direction in order to fix this issue.
can i contact you somehow maybe we can talk about it ?

**Comment by kortana13400** [comment]
Me i can connected with GF 7.9 for sure and i can prove.

**Comment by saitokojiro** [comment]
why won't you help us?

**Comment by bnthomason** [comment]
Because they are good for nothing leechers and think they own their work. But the real owners are the ones who created the game, not them. They don't own anything. Thus, anything they make is public to us, cause they don't own the rights. I would report them as much as possible so github can remove this project from Github.
