### ISSUE TITLE
authentication server

### ISSUE THREAD

**Issue by yoohoseok** [AionGermany/aion-germany#214]
What should be entered as the value of gameserver.version of gameserver.property in order to run the client with GlobalVersion=304 normally?
Or do I need another NO IP file? For example VERSION.DLL?
The authentication server rejects it because the values ​​do not match.

**Comment by kortana13400** [comment]
Me i can connected with GF 7.9 for sure and i can prove.
This version is 7.9.5 KR and can be used by same client GF, so i can connect without problem.

And time that you will spend your time sharing our emulators, we will not help you, ever :)

https://postimg.cc/LYTGt1nR

**Comment by yoohoseok** [comment]
You don't have to tell me. Do it yourself. Many Aion users hate the latest version, and this pack is error prone. There is also a lot of additional mapping.
