### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by lahart99** [AionGermany/aion-germany#220]
Here is the error I'm getting. Any help with this would be highly appreciated!

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\website\classes\classmysql.php:24 Stack trace: #0 C:\xampp\htdocs\website\install.php(159): ClassMysql->connect('localhost', 'root', '123456') #1 {main} thrown in C:\xampp\htdocs\website\classes\classmysql.php on line 24

**Comment by lahart99** [comment]
That worked Thanks for quick reply!!  

Also, i am having issue with Captcha now. The image is not showing up +  error message on bottom of page. 

![image](https://user-images.githubusercontent.com/82407083/161598187-13fc028c-e0a2-45d0-8a3d-b9d4d323f889.png)


And, the other error is this one:

Warning: mysqli_free_result(): Couldn't fetch mysqli_result in C:\xampp\htdocs\website\classes\classmysql.php on line 52

Warning: mysqli_free_result(): Couldn't fetch mysqli_result in C:\xampp\htdocs\website\classes\classmysql.php on line 52

**Comment by nightw0lv** [comment]
dont use this website 
1) live sql queries no cache
2) sql injections and almost every hack work so good you can upload files into server and take access

**Comment by lahart99** [comment]
Thanks, do you have any other sites recommendation?

**Comment by lahart99** [comment]
> dont use this website
> 
> 1. live sql queries no cache
> 2. sql injections and almost every hack work so good you can upload files into server and take access

What's your discord?

**Comment by lahart99** [comment]
> Thera are 2 Includes for mysql commands. Check, which one you are using and which php version you have. If your php is > 7.x, then you need the inc_classmysql_new.php. Rename the old and than rename the _new and try your website again.

Any update?

**Comment by Phantom-KNA** [comment]
> > Thera are 2 Includes for mysql commands. Check, which one you are using and which php version you have. If your php is > 7.x, then you need the inc_classmysql_new.php. Rename the old and than rename the _new and try your website again.
> 
> Any update?

Do you need web for Aion?
