### ISSUE TITLE
Skill Animation from ghostfur

### ISSUE THREAD

**Issue by Falke3434** [AionGermany/aion-germany#23]
Missing item Action in Item template
- can not use skill crads

**Comment by ghostfur** [comment]
I will check now sorry i forgot :D

**Comment by FrozenKiller35** [comment]
SkillAnimationAction:
player.getSkillAnimationList().addSkillAnimation(skinId, minutes);
throws Null Pointer

PlayerEnterWorldService:
for (SkillAnimation skillAnimation : player.getSkillAnimationList().getSkillAnimation()) {
if (skillAnimation.getExpireTime() != 0) {
ExpireTimerTask.getInstance().addTask(skillAnimation, player);
}
}

item_template.xsd
SkillAnimationAction should be edited to this:
	<xs:complexType name="SkillAnimationAction">
		<xs:complexContent>
			<xs:extension base="AbstractItemAction">
				<xs:attribute name="skin_id" type="xs:int"/>
				<xs:attribute name="minutes" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

benas80 commented 27 minutes ago:
If You will try to run these querys there is a bug (Primary key problem). player_events_window08.06.2018.sql player_skill_skins08.06.2018.sql
--

and some more problems ^^

**Comment by ghostfur** [comment]
Falke ! can you see check if you see my new push for the item action! i pushed sec ago

**Comment by FrozenKiller35** [comment]
https://prnt.sc/jtarxp
problem with PacketSendUtility.sendPacket(player, new SM_SKILL_ANIMATION(player));

;)

**Comment by ghostfur** [comment]
I will have a look to see whats wrong! with the packet

**Comment by ghostfur** [comment]
Another fix is coming missing something ells! haha

**Comment by ghostfur** [comment]
I'am almost done!

**Comment by ghostfur** [comment]
Its done uploading now!

**Comment by FrozenKiller35** [comment]
Nice but it won't work...

Skill.java:

if (skillSkin.getTemplate().getSkillGroup().equalsIgnoreCase(skillTemplate.getSkillGroup()) && skillSkin.getIsActive() == 1) {

we don't have skillTemplate.getSkillGroup() so it wont find any skin and sends 0 on attack

**Comment by FrozenKiller35** [comment]
Closed we have another issue to talk ^^
