### ISSUE TITLE
Skill Animation Issues Solved! 

### ISSUE THREAD

**Issue by ghostfur** [AionGermany/aion-germany#28]
I fixing it now its a small error :) in skill animations i forgot something in static_data adding now :)

**Comment by FrozenKiller35** [comment]
Maybe :D
21:44:24.012 ERROR[main]: - Error at [line=1257, column=83158654]: unexpected element (uri:"", local:"skill_animation"). Expected elements are <{}ride>,

**Comment by ghostfur** [comment]
Yes i forgot to put new static_data files inside src 🥇  hahaha

**Comment by ghostfur** [comment]
I Commit now! FrozenKiller The errors should be gone now!

**Comment by FrozenKiller35** [comment]
dont know if you have seen it on other issue.

Nice but it won't work...

Skill.java:

if (skillSkin.getTemplate().getSkillGroup().equalsIgnoreCase(skillTemplate.getSkillGroup()) && skillSkin.getIsActive() == 1) {

we don't have skillTemplate.getSkillGroup() so it wont find any skin and sends 0 on attack

maybe i find some other problems too ^^

**Comment by ghostfur** [comment]
Ow i will check at it now!

**Comment by FrozenKiller35** [comment]
Btw adding a new animation should be active true or ?

And when you add a new animation there should be a new skill icon on HUD ;)

Oh and nice work (works better then first one )

**Comment by ghostfur** [comment]
Frozen i pushed new change can you put  above it :) its say my name now

**Comment by FrozenKiller35** [comment]
Small Bug
https://prnt.sc/jtdjes
Deactivate won't work it always jumps back to active when you click on it

Sure i'll check the new Push

**Comment by ghostfur** [comment]
![1451](https://user-images.githubusercontent.com/13853736/41205821-c4e61110-6cfa-11e8-8b7d-e2dda50fdc0d.PNG)

**Comment by ghostfur** [comment]
What it does now for you frozen?

**Comment by FrozenKiller35** [comment]
Give me a sec ^^

**Comment by FrozenKiller35** [comment]
1: Deactivate working
2: New skill Icon still missing when learn a new animation
3: If you have 1 animation in your list and you learn a new one the new one gets removed if you change the first to deactived
4: New skill animation wont be saved in DB ;)

**Comment by FrozenKiller35** [comment]
For point 3 and 4

ALTER TABLE `player_skill_skins`
MODIFY COLUMN `skin_id`  int(11) NOT NULL DEFAULT 0 AFTER `player_id`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`player_id`, `skin_id`);

;)

**Comment by ghostfur** [comment]
Ow yes indeed :) the sql!

**Comment by ghostfur** [comment]
2: New skill Icon still missing when learn a new animation is still missing?

**Comment by FrozenKiller35** [comment]
wait i'll show you ^^

**Comment by ghostfur** [comment]
![knipsel](https://user-images.githubusercontent.com/13853736/41206102-1358d3d8-6cff-11e8-89da-e4b26dfefff9.PNG)

**Comment by FrozenKiller35** [comment]
SM_SKILL_ANIMATION

Case 0 is for learn and icon display on HUD
but you only use Case 1

and Case 0 should be without the for ()  it always should send only 1 skin on learn ;)

**Comment by ghostfur** [comment]
I will have a look at the file!

**Comment by FrozenKiller35** [comment]
I can do it ;)

**Comment by Onyenofficial** [comment]
Ghosfur leak source bullshit develop becareful Frozen

**Comment by FrozenKiller35** [comment]
@Onyenofficial 
I still remember him (http://forum.ragezone.com/f587/release-aion-lightning-v4-9x-1105747/#post8650044)
but THX

**Comment by ghostfur** [comment]
Lol shut-up Ione You and mhmd stole my stuff and released it on internet hacked my email + posted stupid stuff about me everywhere i never leaked anything thats not free! i just try to help people! like always iam to good for this world pff

**Comment by FrozenKiller35** [comment]
https://image.prntscr.com/image/1SdhBHjkRj_cNlGSxt7UfQ.png

**Comment by ghostfur** [comment]
Oow now i understand Frozenkiller never thought about that :) i will fix it and than commit back!

**Comment by FrozenKiller35** [comment]
already fixed ;)

**Comment by ghostfur** [comment]
Cool What did you do :) frozen? to fix it haha

**Comment by ghostfur** [comment]
I will work on the CP system now because i seen it has some problems!

**Comment by Onyenofficial** [comment]
Just becareful fronzen all know who is ghostfur he leaked all source he want my event engine and stole from dreamaion.net

**Comment by ghostfur** [comment]
Lol i already removed that src after he kicked me from team that event engine is free on internet :D even frozenkiller knows that eventengine so please go away kid :P let us work

**Comment by FrozenKiller35** [comment]
You can see it in a few min (just checking all ;))

@Onyenofficial 
Nothing to steal here our 5.8 is open for all ^^ but again THX ;)

**Comment by ghostfur** [comment]
Your faster than me hahaha!

**Comment by Onyenofficial** [comment]
He can't fix anything got kicked because want to leaked all source pvpall event found on internet?? Keep leaked ghostfur 😂

**Comment by FrozenKiller35** [comment]
Updates / Fixes online ^^

@ghostfur  @Onyenofficial 
Are you talking about Aion 4.5 FFA ?
Oh and time to say GN for me ^^

**Comment by Onyenofficial** [comment]
Nope frozenkiller i talking about leaker i never changed author and add some feature event and i use rift for registration event, @ghosfur here you change author skill skin you got skill skin from my compile on ragezone!

**Comment by ghostfur** [comment]
Whahahahaha from your what? the emulator you stole from archsoft? and released on ragezone haha i never seen it but hans tolt me about it! that was really really leaking!

**Comment by ghostfur** [comment]
You Can Close this :) Frozen Before he put more messengers!

**Comment by Onyenofficial** [comment]
Lol i never change author now here you change author skill skin lmfao keep leeching ghosfur all know who the real dev xD i working on 6.2 and you still 5.8 sure? You need too leaked my source 6.2?

**Comment by ghostfur** [comment]
I already have 6.2 so bye Ione! keep decompiling korean emulators have fun!

**Comment by Onyenofficial** [comment]
Bullshit 6.2? lol leeching ghosfur confimed 😂

**Comment by Onyenofficial** [comment]
You can't proof because you scammer leaker @ghosfur

**Comment by Onyenofficial** [comment]
okay i stop but frozenkiller already know you are leaker all source @ghostfur

**Comment by ghostfur** [comment]
Sure Ione! whatever! all sources i released where free on reg70.tk/forum so someone was before me haha! i only put them on ragezone so not sure what you understand under leaker the only thing i know is that you get nice source from archsoft than release is on ragezone than remove it! thats what i think is more leaking than releasing a source that already was released and was free but its oke for me i really dont care anymore iam 30 years old so why i would do stupid things like you and mhmd ! you guys steal dreamaion source using it for own private server 👍 iam not even using my sources for private servers 💃 Number one rule in devolping never release your own source to others always keep it safe! but its okey people will notice soon anough who the real leaker is ! have a good live ione and leave me alone!
