### ISSUE TITLE
applying sql

### ISSUE THREAD

**Issue by madmax765** [AionGermany/aion-germany#31]
On player_events_window08.06.2018.sql i get this error

`Query:
CREATE TABLE `player_events_window`  (
  `account_id` int(11) NULL DEFAULT NULL,
  `event_id` int(11) NULL DEFAULT NULL,
  `last_stamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `elapsed` double(11, 0) NULL DEFAULT 0,
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

Error occured at:2018-06-11 06:25:39
Line no.:8
Error Code: 1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead`

**Comment by ghostfur** [comment]
Did you try this?

DROP TABLE IF EXISTS `player_events_window`;
CREATE TABLE `player_events_window`  (
  `account_id` int(11) NULL DEFAULT NULL,
  `event_id` int(11) NULL DEFAULT NULL,
  `last_stamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `elapsed` double(11, 0) NULL DEFAULT 0,
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by madmax765** [comment]
Query:
CREATE TABLE player_events_window (
account_id int(11) NULL DEFAULT NULL,
event_id int(11) NULL DEFAULT NULL,
last_stamp timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
elapsed double(11, 0) NULL DEFAULT 0,
PRIMARY KEY (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

Error occured at:2018-06-11 07:08:59
Line no.:8
Error Code: 1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

**Comment by ghostfur** [comment]
-- ----------------------------
-- Table structure for player_events_window
-- ----------------------------
CREATE TABLE `player_events_window` (
  `account_id` int(11) NOT NULL,
  `event_id` int(11) NOT NULL,
  `last_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `elapsed` double(11,0) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by madmax765** [comment]
ok that one worked

**Comment by ghostfur** [comment]
Oke Problem Solved will update the new sql!

**Comment by FrozenKiller35** [comment]
Better set event_id --> primary too this should prevent Null Pointer while inserting

ALTER TABLE `player_events_window`
MODIFY COLUMN `account_id`  int(11) NOT NULL DEFAULT 0 FIRST ,
MODIFY COLUMN `event_id`  int(11) NOT NULL DEFAULT 0 AFTER `account_id`,
ADD PRIMARY KEY (`account_id`, `event_id`);

**Comment by ghostfur** [comment]
Yes ! indeed than this problem is solved 👍
