### ISSUE TITLE
Inventory Shop

### ISSUE THREAD

**Issue by madmax765** [AionGermany/aion-germany#32]
on Inventory Shop - opens the shop in order to sell an item directly. Prices are lower then in NPC shops.

When i go to sell a item. it trows it back into my Inventory Cube. But i can go to a NPC and sell it direct But not from Inventory Shop anymore

level 43 Asmodian Gladiator

**Comment by FrozenKiller35** [comment]
Thx but on offi prices are lower too when selling directly from inventory ;)

**When i go to sell a item. it trows it back into my Inventory Cube:**
Needs to be checked if i have some time ....

**Comment by FrozenKiller35** [comment]
Sell fixed.

> Prices are lower then in NPC shops.

 prices should be lower then selling on NPC ;
