### ISSUE TITLE
Skills problem

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#43]
If You create new character (let's take priest), after enter to the game You have inactive skills:
(client says: You have to learn that skill)

-Healing Light
-Crush

And basic skills (inactive):
-Bandage Heal
-Return (icon is red)

These skills needs level 1 and You have level 1.
 (around lvl 6 these skills are upgraded to lvl 2 and start working)

Why they are inactive ?

**Comment by benas80** [comment]
Somebody help with  this skills on skills bar ?
Why can't use them after creating character and enter to game. (skill "Return" have red color)

**Comment by Falke3434** [comment]
http://falke34.bplaced.net/forums/showthread.php?tid=3109

**Comment by benas80** [comment]
Checking...

**Comment by benas80** [comment]
Yes, now is great :) Thank You
