### ISSUE TITLE
Fix all XSD file include errors in Static_data

### ISSUE THREAD

**Issue by zxysm** [AionGermany/aion-germany#60]
Sorry, I don't really use GITHUB. I don't know how to upload differential files and PULL. I can only package them here. Please integrate ZIP content and fix all XSD file include errors in Static_data.
[static_data.zip](https://github.com/AionGermany/aion-germany/files/2107710/static_data.zip)

**Comment by Falke3434** [comment]
we have Errors in static_data files?
i will check your Files

Thank you
