### ISSUE TITLE
Can't find File for weapon range

### ISSUE THREAD

**Issue by Nimwey** [AionGermany/aion-germany#64]
Hi guys, Can someone tell me plz where i can find weapon range, since gunner has a range of 12 and 20 now which need to be 20 and 25. Also our skills damage seems to be double what i should be can someone help we with that?

**Comment by FrozenKiller35** [comment]
Don't know yet but we will search for it :'O
But this can take a lot of time :(

**Comment by Nimwey** [comment]
Ty i will wait and see for now :( Hope someone has a fix for this problem

**Comment by idhacker542** [comment]
Rip question.
Ask your dev ghosfur nimwey wkwk

**Comment by Nimwey** [comment]
You just keep you mouth shut filtlty leeacher, using Ghostfur's name on things you steal and leak

**Comment by ghostfur** [comment]
Yeah noob mhmd! I dont Care anymore you gona cry when you see or new game maby tonight after work! All intances fixed and so on!! I Will help Falke later but the thing is you check here Everyday for updates ! Leecher noob

**Comment by Nimwey** [comment]
He would not know what do do with them anyway, even fixes he fcks up

**Comment by Chuwi1** [comment]
is there any update about that issue ?

**Comment by ghostfur** [comment]
I can help with that!
