### ISSUE TITLE
Magos and Tokanu Not working properly

### ISSUE THREAD

**Issue by bindaomin** [AionGermany/aion-germany#66]
Location Protective film Not working 
Player enters no invincible gain effect

**Comment by FrozenKiller35** [comment]
Can you explain it a little more i dont play this much to know all of this ^^

**Comment by benas80** [comment]
He mean, on the landing site (in Reshanta Upper) is (purple little transparent) protecting shield (generated by few statues buffs).
If protecting shield is enabled should not pass enemys through this shield. On this server shield is showed but You can fly through. 
I destroyed all statues but shield still is showed. (but not working)
(i think some polygon zone need to be created or some else)

**Comment by bindaomin** [comment]
The current situation is that the shield cannot be controlled to open or close

**Comment by benas80** [comment]
Shield can't be controlled, it's protection against enemy, who fly through and is an enemy should be dead :)

**Comment by ihsan-rahman-tiket** [comment]
this is geo related.. it use 3d area zone

**Comment by SixShoot** [comment]
bindaomin

Are still online does days?
Can you contact me by any chance? I got question
