### ISSUE TITLE
Passkey sequrity option not working

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#73]
I saw little fix in source code protocol but Passkey sequrity option still not working and bugs on the console(if You enter pin code). Maybe You know how to fix this ?

**Comment by FrozenKiller35** [comment]
No Emu has a working 100% Original Passkey system right now :(
No one knows what they changed in encryption etc the patch from Falke is only the first try to make something own 😉

**Comment by benas80** [comment]
No problem, i tryed before to make it works but unsuccessfull.
Yes, there is some kind of encryption.

**Comment by ghostfur** [comment]
Did you guys try this ?

@Override
	protected void readImpl() {
		type = readC();
		unk = readC();
		try {
			passkey = new String(readB(32), "UTF-16le");
			if (type == 2) {
				newPasskey = new String(readB(32), "UTF-16le");
			}
		} catch (Exception e) {
		}
	}

**Comment by benas80** [comment]
This was before in this code and not working.

**Comment by ghostfur** [comment]
Aaah strange will test mine maby i got other script structure 👍
