### ISSUE TITLE
Does the resource below AL-Game\data\static_data\service_bonusattr seem to be working properly?

### ISSUE THREAD

**Issue by zxysm** [AionGermany/aion-germany#74]
I added an F2P account to my MYSQL database. I can see the F2P account prompt when I log into the game, but there is no BUFF bonus in f2p_bonusattr. Similarly, the bonuses such as LegionBonusBuff, PartyBonusBuff, and VIP_Base_CN Buff in service_bonusattr have no effect. Where did I set it incorrectly? I have tried to solve the problem myself, but I failed and asked for help.

**Comment by FrozenKiller35** [comment]
Thx for your report we will see what we can do ;)

**Comment by benas80** [comment]
Hi Ghost :) Very good news :)

**Comment by FrozenKiller35** [comment]
Stats buff's are working but as i can see there is a lot todo with XP and Drop Bonus :O
