### ISSUE TITLE
Skills are not saving

### ISSUE THREAD

**Issue by Woopza** [AionGermany/aion-germany#75]
The skills doesn't save to db, tried to give them all manually to myself but they still disappear after relog. 

Here is my logs; http://www.mediafire.com/file/i9ksigalt9fd6ns/console.log

**Comment by benas80** [comment]
You have lots of bugs while gs loading data so:
1) Make a clean database install (from this server files)
2) Compile this game server
3) Use this data files (not other or mix)

**Comment by Woopza** [comment]
I saw this after posting the issue; https://github.com/AionGermany/aion-germany/issues/40 and it fixed my problem. Will update if I face other issues. Thanks all for support and share.

P.S. I would love to work on a web page development for this, soon.

**Comment by benas80** [comment]
Great :)
