### ISSUE TITLE
StartGS erro

### ISSUE THREAD

**Issue by qxpf666** [AionGermany/aion-germany#76]
Starting Aion German Version 5.x Game Server.

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0
18:06:53.067 ERROR[main]: - Critical Error - Thread: main terminated abnormaly: java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    com/aionemu/gameserver/utils/javaagent/JavaAgentUtils.checkObjectCallback()Z @90: iload_3
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ac0 0017 2ab4 003b 01b8 0041 4c2b b600
    0x0000010: 4499 0007 03a7 0007 03a7 0003 3e2b b600
    0x0000020: 4699 000e 2bb6 004a c000 4cb6 004f 3e2a
    0x0000030: c000 172a b400 3b01 1dbb 004c 595d 58b7
    0x0000040: 0052 b800 564c 2bb6 0058 9900 0e2b b600
    0x0000050: 59c0 004c b600 4fac 1dac 1dac
  Stackmap Table:
    append_frame(@24,Object[#55])
    same_locals_1_stack_item_frame(@28,Integer)
    full_frame(@47,{Object[#20],Top,Top,Integer},{})
    same_frame(@88)

java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    com/aionemu/gameserver/utils/javaagent/JavaAgentUtils.checkObjectCallback()Z @90: iload_3
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ac0 0017 2ab4 003b 01b8 0041 4c2b b600
    0x0000010: 4499 0007 03a7 0007 03a7 0003 3e2b b600
    0x0000020: 4699 000e 2bb6 004a c000 4cb6 004f 3e2a
    0x0000030: c000 172a b400 3b01 1dbb 004c 595d 58b7
    0x0000040: 0052 b800 564c 2bb6 0058 9900 0e2b b600
    0x0000050: 59c0 004c b600 4fac 1dac 1dac
  Stackmap Table:
    append_frame(@24,Object[#55])
    same_locals_1_stack_item_frame(@28,Integer)
    full_frame(@47,{Object[#20],Top,Top,Integer},{})
    same_frame(@88)

        at com.aionemu.gameserver.GameServer.initUtilityServicesAndConfig(GameServer.java:497) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.GameServer.main(GameServer.java:239) ~[AL-Game.jar:na]

Server terminated abnormaly ...

Server terminated ...

**Comment by benas80** [comment]
Server starting good, no errors.

**Comment by qxpf666** [comment]
run with jdk 1.7 or 1.8

**Comment by FrozenKiller35** [comment]
GameServer needs Java 7 (1.7)
Login and Chat-Server need Java 8 (1.8)

Add SET PATH="C:\Program Files\Java\jdk1.7.0_80\bin" to your GameServer PanelGS.bat and StartGS.bat 

Example: 
@ECHO off
TITLE Aion German - Game Server Console
SET PATH="C:\Program Files\Java\jdk1.7.0_80\bin"
:START

**Comment by qxpf666** [comment]
thanks
