### ISSUE TITLE
Ophidan Bridge - small problem

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#77]
Great is Ophidan Bridge working :) but:
There is second chest (supply) on the left side (bug if You click on it)

**Comment by FrozenKiller35** [comment]
If you talk from:
NPC 702659 (Shining Chest of the Returnees) its removed now

Todo: Instance exit isnt working

**Comment by benas80** [comment]
I mean: Beritra Booty Chest (id: 702959), on the left side of Exit teleporter (after boss kill).

**Comment by FrozenKiller35** [comment]
Fixed.

You need Quest 16977 
https://aioncodex.com/en/quest/16977/?sl=1
