### ISSUE TITLE
Forum???

### ISSUE THREAD

**Issue by Zolyd** [AionGermany/aion-germany#79]
Hey,
kann man sich nicht mehr bei euch im Forum anmelden???

**Comment by Woopza** [comment]
I can't register to the forum aswell, it won't send confirmation mail. Would be awesome if you can confirm manually, my username is Woopza

**Comment by FrozenKiller35** [comment]
Please try again Falke already has cleaned all unconfirmed accounts :O

**Comment by Falke3434** [comment]
Register in Forum -> wait of Activation EMail -> Activate your Account -> Finish!

**Comment by Zolyd** [comment]
Klappt nicht bekomme keine Mail habe es schon 4 tage hinter einander versucht 

Account Name Tyden 

Auch nach nochmals schicken des Aktivierungs links geht es nicht

**Comment by Falke3434** [comment]
Die Mail wird vom System automatisch verschickt (funktioniert)!
Spam ordner überprüfen oder eben eine richtige EMail benutzen

**Comment by Zolyd** [comment]
Kann es sein das euer System Gmail nicht nimmt? Habe es mit Yahoo und Gmail versucht im Spam ist auch nichts gelandet :/

**Comment by Falke3434** [comment]
Gmail geht. Habe dich jetzt aktiviert (normal tue ich dies nicht)
Closed
