### ISSUE TITLE
Base.spawnAttackers -> Null Pointer

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#80]
In source Base->spawnAttackers:
I was tryed to remove and fix this (to avoid throw nullpointer) this line 449: 
throw new NullPointerException("Base:" + getId() + " flag is null!");
I receive nullpointer today testing.

2018-07-15 10:43:05,579 Exception in a Runnable execution:
java.lang.NullPointerException: null
	at com.aionemu.gameserver.services.base.Base.spawnAttackers(Base.java:451) ~[AL-Game.jar:na]

Maybe this should be ignore.

**Comment by FrozenKiller35** [comment]
Do you know wich Base ID ?

**Comment by benas80** [comment]
I will try to catch this ID
