### ISSUE TITLE
Shugo Sweep

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#83]
Shugo Sweep(Lucky Dices) icon don't shot on client.
Is some client launcher parameter needed ?

**Comment by FrozenKiller35** [comment]
Client modding ...

**Comment by ghostfur** [comment]
Try This Client Patch:
https://mega.nz/#!8x5DnLyL!c4owuRIpxzXo6CGx_LK3ysWxTJARbjGBlIEjnpqA2Ug

**Comment by benas80** [comment]
YEA! :D its working! 
Great job really nice :)

**Comment by ghostfur** [comment]
No Problem! 👍

**Comment by FrozenKiller35** [comment]
Closed
