### ISSUE TITLE
Can't promote my character to GM status

### ISSUE THREAD

**Issue by HaoNYUTON** [AionGermany/aion-germany#89]
It is quite possible that I don't understand how to use command //promote correctly, but I've tried to use it as syntax says, either like //promote <charname> 3 3, or //promote <charname> 3 Head-GM, and neither is working. What am I doing wrong?

**Comment by FrozenKiller35** [comment]
Maybe its buggy but you can change your account in LoginServer DB to access_level 6 for GM
If i have some free time i'll try to fix it ;)

**Comment by FrozenKiller35** [comment]
Update:
You should try this:

//promote CHARNAME accesslevel 3

Example:
//promote Frozenkiller accesslevel 3

**Comment by HaoNYUTON** [comment]
Thanks, I'll try!

**Comment by HaoNYUTON** [comment]
That works, thanks!
