### ISSUE TITLE
Build Gameserver error

### ISSUE THREAD

**Issue by Darksoz123** [AionGermany/aion-germany#90]
![build server error](https://user-images.githubusercontent.com/31354607/43425629-d3656f3e-9418-11e8-9235-269f4094c7f0.jpg)

I don't know how to solve this :C

**Comment by madmax765** [comment]
built ok for me. you using have 7 ?

**Comment by Darksoz123** [comment]
No, I’m using JDK 8. Do I need to use JDK 7?

**Comment by FrozenKiller35** [comment]
I think there is missing someting did you try to redownload it and try again ?

**Comment by Darksoz123** [comment]
Thank you FrozenKiller35 that fix the problem :D
