### ISSUE TITLE
Log in Error

### ISSUE THREAD

**Issue by Chuwi1** [AionGermany/aion-germany#91]
Chat , Log in and Game built are seen good, they say builds are successfull.

but after all when I try to log in, Client says, **Can not connect to the authorization server...**

what might be the reason ?

Thanks

**Comment by ghostfur** [comment]
Maby AL-Game\config\network Files are not set? 

Or you are not using the Aion Germany Launcher? 
https://github.com/AionGermany/aion-germany/blob/master/AL-Tools/AionLauncherEU_5.x.rar
Open launcher.config and edit TYPYOURIPHERE with your ip adress

-ip:TYPYOURIPHERE -port:2106 -cc:2 -lang:enu -noweb -noauthgg -nowebshop -f2p -megaphone -aiontv

Is it a clean client  you are using?

**Comment by Chuwi1** [comment]
thank you, it is my fault, I was not configuring the config files...

Thanks..

**Comment by ghostfur** [comment]
No Problem ;)
