### ISSUE TITLE
Error List (CP, SKILL, MANASTONE)

### ISSUE THREAD

**Issue by juangjaguar** [AionGermany/aion-germany#93]
CP (Creative Point) if apply will minus (-) [Just Display]
Skill range (ranger, gunner) not fix (skill 25m but they in game only 16-18m)
manastone (power, will, agi, etc (+4) - (+12) Need Fix

**Comment by juangjaguar** [comment]
This is manastone power will agi etc (+4)-(+10)
(+11)-(+12) //on working

<item_template id="167010274" name="Manastone: Power +4" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705579" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ATTACK" value="6" bonus="true"/>
            <add name="PHYSICAL_DEFENSE" value="99" bonus="true"/>          
            <add name="POWER" value="4" bonus="true"/>      
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010275" name="Manastone: HP +4" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705581" activate_count="1">
        <modifiers>
            <add name="MAXHP" value="92" bonus="true"/>
            <add name="BLOCK" value="23" bonus="true"/>
            <add name="REGEN_HP" value="2" bonus="true"/>   
            <add name="HEALTH" value="4" bonus="true"/> 
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010276" name="Manastone: Agility +4" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705583" activate_count="1">
        <modifiers>
            <add name="CONCENTRATION" value="2" bonus="true"/>
            <add name="PARRY" value="25" bonus="true"/>
            <add name="EVASION" value="16" bonus="true"/>
            <add name="PHYSICAL_CRITICAL_RESIST" value="24" bonus="true"/>
            <add name="AGILITY" value="4" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010277" name="Manastone: Precision +4" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705585" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ACCURACY" value="30" bonus="true"/>
            <add name="PHYSICAL_CRITICAL" value="15" bonus="true"/>
            <add name="MAGICAL_ACCURACY" value="24" bonus="true"/>
            <add name="ACCURACY" value="4" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010278" name="Manastone: Knowledge +4" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705587" activate_count="1">
        <modifiers>
            <add name="BOOST_MAGICAL_SKILL" value="24" bonus="true"/>
            <add name="MAGICAL_CRITICAL" value="9" bonus="true"/>
            <add name="MAGIC_SKILL_BOOST_RESIST" value="42" bonus="true"/>
            <add name="KNOWLEDGE" value="4" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010279" name="Manastone: Will +4" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705589" activate_count="1">
        <modifiers>
            <add name="MAXMP" value="99" bonus="true"/>
            <add name="MAGICAL_RESIST" value="14" bonus="true"/>
            <add name="MAGICAL_CRITICAL_RESIST" value="13" bonus="true"/>
            <add name="REGEN_MP" value="1" bonus="true"/>
            <add name="WILL" value="4" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010280" name="Manastone: Power +5" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705603" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ATTACK" value="8" bonus="true"/>
            <add name="PHYSICAL_DEFENSE" value="123" bonus="true"/>
            <add name="POWER" value="5" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010281" name="Manastone: HP +5" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705603" activate_count="1">
        <modifiers>
            <add name="MAXHP" value="115" bonus="true"/>
            <add name="BLOCK" value="29" bonus="true"/>
            <add name="REGEN_HP" value="2" bonus="true"/>
            <add name="HEALTH" value="5" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010282" name="Manastone: Agility +5" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705603" activate_count="1">
        <modifiers>
            <add name="CONCENTRATION" value="3" bonus="true"/>
            <add name="PARRY" value="31" bonus="true"/>
            <add name="EVASION" value="20" bonus="true"/>
            <add name="PHYSICAL_CRITICAL_RESIST" value="30" bonus="true"/>          
            <add name="AGILITY" value="5" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010283" name="Manastone: Precision +5" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705609" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ACCURACY" value="39" bonus="true"/>
            <add name="PHYSICAL_CRITICAL" value="19" bonus="true"/>
            <add name="MAGICAL_ACCURACY" value="30" bonus="true"/>          
            <add name="ACCURACY" value="5" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010284" name="Manastone: Knowledge +5" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705611" activate_count="1">
        <modifiers>
            <add name="BOOST_MAGICAL_SKILL" value="30" bonus="true"/>
            <add name="MAGICAL_CRITICAL" value="11" bonus="true"/>
            <add name="MAGIC_SKILL_BOOST_RESIST" value="15" bonus="true"/>
            <add name="KNOWLEDGE" value="5" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010285" name="Manastone: Will +5" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705613" activate_count="1">
        <modifiers>
            <add name="MAXMP" value="124" bonus="true"/>
            <add name="MAGICAL_RESIST" value="17" bonus="true"/>
            <add name="MAGICAL_CRITICAL_RESIST" value="16" bonus="true"/>
            <add name="REGEN_MP" value="1" bonus="true"/>
            <add name="WILL" value="5" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010286" name="Manastone: Power +6" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705627" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ATTACK" value="9" bonus="true"/>
            <add name="PHYSICAL_DEFENSE" value="146" bonus="true"/>
            <add name="POWER" value="6" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010287" name="Manastone: HP +6" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705629" activate_count="1">
        <modifiers>
            <add name="MAXHP" value="138" bonus="true"/>
            <add name="BLOCK" value="24" bonus="true"/>
            <add name="REGEN_HP" value="2" bonus="true"/>
            <add name="HEALTH" value="6" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010288" name="Manastone: Agility +6" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705631" activate_count="1">
        <modifiers>
            <add name="CONCENTRATION" value="3" bonus="true"/>
            <add name="PARRY" value="37" bonus="true"/>
            <add name="EVASION" value="23" bonus="true"/>
            <add name="PHYSICAL_CRITICAL_RESIST" value="36" bonus="true"/>
            <add name="AGILITY" value="6" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010289" name="Manastone: Precision +6" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705633" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ACCURACY" value="47" bonus="true"/>
            <add name="PHYSICAL_CRITICAL" value="23" bonus="true"/>
            <add name="MAGICAL_ACCURACY" value="36" bonus="true"/>
            <add name="ACCURACY" value="6" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010290" name="Manastone: Knowledge +6" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705635" activate_count="1">
        <modifiers>
            <add name="BOOST_MAGICAL_SKILL" value="37" bonus="true"/>
            <add name="MAGICAL_CRITICAL" value="44" bonus="true"/>
            <add name="MAGIC_SKILL_BOOST_RESIST" value="62" bonus="true"/>
            <add name="KNOWLEDGE" value="6" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010291" name="Manastone: Will +6" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="UNIQUE" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705637" activate_count="1">
        <modifiers>
            <add name="MAXMP" value="148" bonus="true"/>
            <add name="MAGICAL_RESIST" value="21" bonus="true"/>
            <add name="MAGICAL_CRITICAL_RESIST" value="19" bonus="true"/>
            <add name="REGEN_MP" value="1" bonus="true"/>
            <add name="WILL" value="6" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010292" name="Manastone: Power +7" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705651" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ATTACK" value="11" bonus="true"/>
            <add name="PHYSICAL_DEFENSE" value="170" bonus="true"/>
            <add name="POWER" value="7" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010293" name="Manastone: HP +7" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705653" activate_count="1">
        <modifiers>
            <add name="MAXHP" value="161" bonus="true"/>
            <add name="BLOCK" value="40" bonus="true"/>
            <add name="REGEN_HP" value="3" bonus="true"/>
            <add name="HEALTH" value="7" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010294" name="Manastone: Agility +7" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705655" activate_count="1">
        <modifiers>
            <add name="CONCENTRATION" value="4" bonus="true"/>
            <add name="PARRY" value="44" bonus="true"/>
            <add name="EVASION" value="27" bonus="true"/>
            <add name="PHYSICAL_CRITICAL_RESIST" value="41" bonus="true"/>
            <add name="AGILITY" value="7" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010295" name="Manastone: Precision +7" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705657" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ACCURACY" value="53" bonus="true"/>
            <add name="PHYSICAL_CRITICAL" value="27" bonus="true"/>
            <add name="MAGICAL_ACCURACY" value="42" bonus="true"/>
            <add name="ACCURACY" value="7" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010296" name="Manastone: Knowledge +7" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705659" activate_count="1">
        <modifiers>
            <add name="BOOST_MAGICAL_SKILL" value="53" bonus="true"/>
            <add name="MAGICAL_CRITICAL" value="16" bonus="true"/>
            <add name="MAGIC_SKILL_BOOST_RESIST" value="72" bonus="true"/>
            <add name="KNOWLEDGE" value="7" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010297" name="Manastone: Will +7" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705661" activate_count="1">
        <modifiers>
            <add name="MAXMP" value="173" bonus="true"/>
            <add name="MAGICAL_RESIST" value="24" bonus="true"/>
            <add name="MAGICAL_CRITICAL_RESIST" value="23" bonus="true"/>
            <add name="REGEN_MP" value="1" bonus="true"/>
            <add name="WILL" value="7" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010298" name="Manastone: Power +8" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705675" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ATTACK" value="12" bonus="true"/>
            <add name="PHYSICAL_DEFENSE" value="192" bonus="true"/>
            <add name="POWER" value="8" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010299" name="Manastone: HP +8" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705677" activate_count="1">
        <modifiers>
            <add name="MAXHP" value="184" bonus="true"/>
            <add name="BLOCK" value="46" bonus="true"/>
            <add name="REGEN_HP" value="3" bonus="true"/>
            <add name="HEALTH" value="8" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010300" name="Manastone: Agility +8" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705679" activate_count="1">
        <modifiers>
            <add name="CONCENTRATION" value="5" bonus="true"/>
            <add name="PARRY" value="50" bonus="true"/>
            <add name="EVASION" value="31" bonus="true"/>
            <add name="PHYSICAL_CRITICAL_RESIST" value="47" bonus="true"/>
            <add name="AGILITY" value="8" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010301" name="Manastone: Precision +8" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705681" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ACCURACY" value="62" bonus="true"/>
            <add name="PHYSICAL_CRITICAL" value="30" bonus="true"/>
            <add name="MAGICAL_ACCURACY" value="48" bonus="true"/>
            <add name="ACCURACY" value="8" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010302" name="Manastone: Knowledge +8" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705683" activate_count="1">
        <modifiers>
            <add name="BOOST_MAGICAL_SKILL" value="49" bonus="true"/>
            <add name="MAGICAL_CRITICAL" value="18" bonus="true"/>
            <add name="MAGIC_SKILL_BOOST_RESIST" value="81" bonus="true"/>
            <add name="KNOWLEDGE" value="8" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010303" name="Manastone: Will +8" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705685" activate_count="1">
        <modifiers>
            <add name="MAXMP" value="197" bonus="true"/>
            <add name="MAGICAL_RESIST" value="27" bonus="true"/>
            <add name="MAGICAL_CRITICAL_RESIST" value="26" bonus="true"/>
            <add name="REGEN_MP" value="2" bonus="true"/>
            <add name="WILL" value="8" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010304" name="Manastone: Power +9" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705699" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ATTACK" value="14" bonus="true"/>
            <add name="PHYSICAL_DEFENSE" value="215" bonus="true"/>
            <add name="POWER" value="9" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010305" name="Manastone: HP +9" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705701" activate_count="1">
        <modifiers>
            <add name="MAXHP" value="206" bonus="true"/>
            <add name="BLOCK" value="51" bonus="true"/>
            <add name="REGEN_HP" value="3" bonus="true"/>
            <add name="HEALTH" value="9" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010306" name="Manastone: Agility +9" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705703" activate_count="1">
        <modifiers>
            <add name="CONCENTRATION" value="5" bonus="true"/>
            <add name="PARRY" value="56" bonus="true"/>
            <add name="EVASION" value="35" bonus="true"/>
            <add name="PHYSICAL_CRITICAL_RESIST" value="53" bonus="true"/>
            <add name="AGILITY" value="9" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010307" name="Manastone: Precision +9" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705705" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ACCURACY" value="70" bonus="true"/>
            <add name="PHYSICAL_CRITICAL" value="34" bonus="true"/>
            <add name="MAGICAL_ACCURACY" value="53" bonus="true"/>
            <add name="ACCURACY" value="9" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010308" name="Manastone: Knowledge +9" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705707" activate_count="1">
        <modifiers>
            <add name="BOOST_MAGICAL_SKILL" value="55" bonus="true"/>
            <add name="MAGICAL_CRITICAL" value="20" bonus="true"/>
            <add name="MAGIC_SKILL_BOOST_RESIST" value="91" bonus="true"/>
            <add name="KNOWLEDGE" value="9" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010309" name="Manastone: Will +9" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705709" activate_count="1">
        <modifiers>
            <add name="MAXMP" value="222" bonus="true"/>
            <add name="MAGICAL_RESIST" value="31" bonus="true"/>
            <add name="MAGICAL_CRITICAL_RESIST" value="29" bonus="true"/>
            <add name="REGEN_MP" value="2" bonus="true"/>
            <add name="WILL" value="9" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010310" name="Manastone: Power +10" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705723" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ATTACK" value="15" bonus="true"/>
            <add name="PHYSICAL_DEFENSE" value="237" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010311" name="Manastone: HP +10" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705725" activate_count="1">
        <modifiers>
            <add name="MAXHP" value="229" bonus="true"/>
            <add name="BLOCK" value="57" bonus="true"/>
            <add name="REGEN_HP" value="4" bonus="true"/>
            <add name="HEALTH" value="10" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010312" name="Manastone: Agility +10" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705727" activate_count="1">
        <modifiers>
            <add name="CONCENTRATION" value="6" bonus="true"/>
            <add name="PARRY" value="62" bonus="true"/>
            <add name="EVASION" value="39" bonus="true"/>
            <add name="PHYSICAL_CRITICAL_RESIST" value="58" bonus="true"/>
            <add name="AGILITY" value="10" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010313" name="Manastone: Precision +10" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705729" activate_count="1">
        <modifiers>
            <add name="PHYSICAL_ACCURACY" value="77" bonus="true"/>
            <add name="PHYSICAL_CRITICAL" value="38" bonus="true"/>
            <add name="MAGICAL_ACCURACY" value="59" bonus="true"/>
            <add name="ACCURACY" value="10" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010314" name="Manastone: Knowledge +10" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705731" activate_count="1">
        <modifiers>
            <add name="BOOST_MAGICAL_SKILL" value="61" bonus="true"/>
            <add name="MAGICAL_CRITICAL" value="23" bonus="true"/>
            <add name="MAGIC_SKILL_BOOST_RESIST" value="100" bonus="true"/>
            <add name="KNOWLEDGE" value="10" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>
    <item_template id="167010315" name="Manastone: Will +10" level="70" mask="12414" category="MANASTONE" max_stack_count="10000" item_type="NORMAL" quality="EPIC" price="5" race="PC_ALL" restrict="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" desc="1705733" activate_count="1">
        <modifiers>
            <add name="MAXMP" value="246" bonus="true"/>
            <add name="MAGICAL_RESIST" value=	"34" bonus="true"/>
            <add name="MAGICAL_CRITICAL_RESIST" value="32" bonus="true"/>
            <add name="REGEN_MP" value="2" bonus="true"/>
            <add name="WILL" value="10" bonus="true"/>
        </modifiers>
        <actions>
            <enchant count="50"/>
        </actions>
    </item_template>

**Comment by Falke3434** [comment]
Manastone Fix with rev275

**Comment by FrozenKiller35** [comment]
Skill range fixed ;)

**Comment by Chuwi1** [comment]
spellbook auto attack range is still short than normal. it is now 15m...

**Comment by Chuwi1** [comment]
and also, rangers bestial fury buff doesnt decrease attack range of bow,  assassin rune skills don't work.. they dont rune up the opponent correctly..

isnt it possible to change xml files with original extracted ones ? it is utf 16 and, cant it be configured to this emulator ?

**Comment by FrozenKiller35** [comment]
Skill range before my fix was always 12 - 13 now its related to weapon etc

rangers bestial fury buff  <-- thats a skill template problem
Assa rune problem is known (since 4.x ) but i have no solution yet

No you can't use Original XML files the whole src of this or other Emu's has to be rewritten ( min 50%)

Oh and my test char was an Mage but with Orb maybe if i have more time i can find something and fix it

But for now i think its working much better then with a range of 12 or 14 (no matter what skill or weapon ;) )

**Comment by juangjaguar** [comment]
thankyou verymuch falkeee <3 love u
