### ISSUE TITLE
Could not restore f2p time for accountId: 2 from DB: Unknown column

### ISSUE THREAD

**Issue by clavera** [AionGermany/aion-germany#94]
![f2p time](https://user-images.githubusercontent.com/42079372/44153930-a6415f96-a0d3-11e8-8be8-decbf0b57068.jpg)

**Comment by FrozenKiller35** [comment]
Use the SQL updates ....

**Comment by madmax765** [comment]
I have the same trouble but I did apply F2p Update - 25.05.2018

**Comment by FrozenKiller35** [comment]
Found it someone changed account_id to player_id ....

Added a new SQL update for that problem ;)
