### ISSUE TITLE
item_templates and item_upgrades 

### ISSUE THREAD

**Issue by juangjaguar** [AionGermany/aion-germany#96]
Item_Template for Manastone +4 - +12
and add item_upgrade plume to gold plume
[Manastone 4-12.txt](https://github.com/AionGermany/aion-germany/files/2300619/Manastone.4-12.txt)
[item_upgrade.txt](https://github.com/AionGermany/aion-germany/files/2300620/item_upgrade.txt)

**Comment by FrozenKiller35** [comment]
Your Item Upgrade won't be used by us because GF uses other upgrade in Client then NA and maybe others, so we can't use them (We only support GF / EU Client)

Manastone has still to be tested ...

**Comment by juangjaguar** [comment]
maybe i use with NA client

**Comment by Falke3434** [comment]
Manastone Fix with rev275
