### ISSUE TITLE
Error build chatserver

### ISSUE THREAD

**Issue by hnomkeng** [AionGermany/aion-germany#98]
Git commit : db03c4a00e53b19b8e6fb93fe9645180abe4825b
JDK : jdk1.8.0_181
OS : 10 Pro

![image](https://user-images.githubusercontent.com/9112684/44618926-7de68980-a8a9-11e8-8e96-876ecbea1bee.png)

Edit : JDK version

**Comment by FrozenKiller35** [comment]
Should be fixed with latest REV ;)
